version: '3.9'

services:
  port-remapper:
    build: .
    container_name: port-remapper
    cap_add:
      - NET_ADMIN
    networks:
      mymacvlannet:
        ipv4_address: 192.168.7.250
    restart: unless-stopped

networks:
  mymacvlannet:
    external: true

